name: Build Bazzite Hyprland Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ublue-os/bluebuild/.github/workflows/release.yml@main
    with:
      image_name: bazzite-hyprland-infurno

