name: Build Bazzite Hyprland Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ublue-os/image-template/.github/workflows/build.yml@main
    with:
      image_name: bazzite-hyprland-infurno

  disk:
    needs: build
    uses: ublue-os/image-template/.github/workflows/disk.yml@main
    with:
      IMAGE_NAME: bazzite-hyprland-infurno
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
      DEFAULT_TAG: latest

