name: Build Bazzite Hyprland Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ublue-os/ublue-main/.github/workflows/image.yaml@main
    with:
      image-name: bazzite-hyprland-infurno

